### ISSUE TITLE
Add Image and Add Audio buttons do not accept dragging files

### ISSUE THREAD

**Issue by batchku** [irllabs/simplevr#49]
![image](https://user-images.githubusercontent.com/518356/111365568-e0fac000-864f-11eb-9573-7a2dd8bc4d58.png)

**Comment by lazarmitic** [comment]
Added option for drag-drop files for Audio and Image selectors. Deployed on production.

What would be nice to have is if user tries to drag audio file on image input to show warning/error message to user explaining that file does not have valid format.

@mericda Should I just come up with dialogs for progress/error/warrning based on Material UI library that I'm using, or should I wait for you to put something together.

**Comment by mericda** [comment]
@lazarmitic can we use Material Snackbars (https://material.io/components/snackbars) and show a message? "Invalid file type. Supported file types for audio files: .MP3 , .WAV." also, "File is too big. Maximum supported file size is 5 MB (5096 KBs)"  etc.

**Comment by lazarmitic** [comment]
Yes, I will add that.

**Comment by lazarmitic** [comment]
Fixed, files type and size are now checked, in case of invalid file size or type, snackbar notification will let user know.
