### ISSUE TITLE
Can't tell if my project is saved, or saving, or needs to be saved

### ISSUE THREAD

**Issue by batchku** [irllabs/simplevr#54]
![image](https://user-images.githubusercontent.com/518356/111375117-207ad980-865b-11eb-8c99-c073065268a3.png)

This UI must indicate to me whether:
- my project is saved
- my project is saving
- my project needs to be saved

**Comment by lazarmitic** [comment]
![image](https://user-images.githubusercontent.com/7648077/111393435-0f60b580-86b9-11eb-9c3b-ff0b48cf91f3.png)

When clicking save, circle progress icon will show while save lasts - I'm not sure how to solve last option - maybe adding red circle in top right corner of save icon (like a notification dot). @mericda please help :)
