### ISSUE TITLE
There is no way to exit preview mode

### ISSUE THREAD

**Issue by batchku** [irllabs/simplevr#56]
I need a button that allows me to get back to the editor

**Comment by lazarmitic** [comment]
Added back button in top left corner. @mericda please review if it looks fine.

**Comment by mericda** [comment]
@lazarmitic it looks fine, but that button doesn't do anything when I'm viewing a public story. Expected action would be taking  viewer back to the home page of the app if they're viewing a public story. Can we fix this?

**Comment by lazarmitic** [comment]
Yes, definitely

**Comment by lazarmitic** [comment]
Fixed, if public story link is opened from outside of the application, back button will send user to landing page.
