### ISSUE TITLE
Can not edit experiences on iPad

### ISSUE THREAD

**Issue by batchku** [irllabs/simplevr#60]
When opening the app in chrome on an iPad, it is not possible to click on the edit button of a story because it only appears on rollover

Recommendation to move the buttons to the white title bar and make them always visible

**Comment by lazarmitic** [comment]
@mericda can you update Figma design for this and I will update in the app side as well.

**Comment by lazarmitic** [comment]
We need this for all 'mouseover' actions.

**Comment by lazarmitic** [comment]
I moved those options to card header section (for story cards on landing page, and room card in editor).
